import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FavoritesProvider } from "@/context/FavoritesContext";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Dashboard - Product Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.className} antialiased`}
      >
        <FavoritesProvider>
          <main className="container mx-auto px-4 py-8 pb-20">
            <Header />
            {children}
          </main>
        </FavoritesProvider>
      </body>
    </html>
  );
}
